name: notes-ai
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.11
    - openai
    - python-dotenv
    - qdrant-client
    - streamlit
    - pydub
    - ffmpeg
    - pip
    - pip:
          - streamlit-audiorecorder
